version: '3'

services:
  db_microservice_1:
    image: postgres:12
    environment:
      POSTGRES_DB: db_microservice_1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: azerty
    ports:
      - 5434:5432
    networks:
      - my_local_network
  db_microservice_2:
    image: postgres:12
    environment:
      POSTGRES_DB: db_microservice_1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: azerty
    ports:
      - 5435:5432
    networks:
      - my_local_network
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: azerty
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - 5050:5050
    networks:
      - my_local_network
networks:
  my_local_network:
    driver: bridge
